### ISSUE TITLE
some question about getting the kinetics(关于获得数据的一些问题)

### ISSUE THREAD

**Issue by ImmortalCi** [AcherStyx/kinetics-dataset-downloader#1]
很感谢你提供自动下载、分类kinetics400数据集的脚本！我在运行脚本的时候发现每个数据集压缩包文件是一闪而过的，大小不一但是都很小只有几十M，是多线程下每个压缩包都还在继续下载嘛？
另外，有个小问题：scripts文件夹下的脚本download_links.sh在被k400.sh调用的时候是download_link.sh哦，作者可以改其中一个，否则会报错不存在。
非常期待得到你的答复！
![微信截图_20211030233220](https://user-images.githubusercontent.com/74886609/139539596-969f592e-cf7a-4928-8c0c-26b36a91716e.png)

**Comment by Yaojie-Shen** [comment]
> 很感谢你提供自动下载、分类kinetics400数据集的脚本！我在运行脚本的时候发现每个数据集压缩包文件是一闪而过的，大小不一但是都很小只有几十M，是多线程下每个压缩包都还在继续下载嘛？
> 
> 另外，有个小问题：scripts文件夹下的脚本download_links.sh在被k400.sh调用的时候是download_link.sh哦，作者可以改其中一个，否则会报错不存在。
> 
> 非常期待得到你的答复！
> 
> ![微信截图_20211030233220](https://user-images.githubusercontent.com/74886609/139539596-969f592e-cf7a-4928-8c0c-26b36a91716e.png)
> 
> 

所有的下载和解压缩都是多进程并行的，准确来说是一个批量一个批量的并行，因为考虑到开太多有些机器性能不好可能会卡，或者网络不好。如果网不好（连aws存储国内偶尔会断连），还是不要直接用k400.sh这个脚本为好，下载部分容易出问题，用个啥下载管理软件把下载链接导进去也好，uget之类的。
每一步操作拆封的对应脚本都在./scripts下，里面的process_num变量可以调整并行的数量，下载和解压都行。

十几M的我不确定是不是下载失败了。但是刚开始会自动下载链接的集合、csv标注，这部分只有MB级别的大小。图中的part_###才是视频部分，每个文件1.5GB左右。

命名问题是我疏忽了，大概是因为使用pycharm同步，重命名后，推到server上的旧脚本还留着，测试就没有发现问题。感谢～

**Comment by ImmortalCi** [comment]
> > 很感谢你提供自动下载、分类kinetics400数据集的脚本！我在运行脚本的时候发现每个数据集压缩包文件是一闪而过的，大小不一但是都很小只有几十M，是多线程下每个压缩包都还在继续下载嘛？
> > 另外，有个小问题：scripts文件夹下的脚本download_links.sh在被k400.sh调用的时候是download_link.sh哦，作者可以改其中一个，否则会报错不存在。
> > 非常期待得到你的答复！
> > ![微信截图_20211030233220](https://user-images.githubusercontent.com/74886609/139539596-969f592e-cf7a-4928-8c0c-26b36a91716e.png)
> 
> 所有的下载和解压缩都是多进程并行的，准确来说是一个批量一个批量的并行，因为考虑到开太多有些机器性能不好可能会卡，或者网络不好。如果网不好（连aws存储国内偶尔会断连），还是不要直接用k400.sh这个脚本为好，下载部分容易出问题，用个啥下载管理软件把下载链接导进去也好，uget之类的。 每一步操作拆封的对应脚本都在./scripts下，里面的process_num变量可以调整并行的数量，下载和解压都行。
> 
> 十几M的我不确定是不是下载失败了。但是刚开始会自动下载链接的集合、csv标注，这部分只有MB级别的大小。图中的part_###才是视频部分，每个文件1.5GB左右。
> 
> 命名问题是我疏忽了，大概是因为使用pycharm同步，重命名后，推到server上的旧脚本还留着，测试就没有发现问题。感谢～

感谢你的解答~不知你有没有做提取 RGB 帧和光流的工作呢？想大致了解下这份数据集全部处理好需要多大的空间，我好方便预留足够的空间给它。
再次表示感谢~

**Comment by ImmortalCi** [comment]
> > 很感谢你提供自动下载、分类kinetics400数据集的脚本！我在运行脚本的时候发现每个数据集压缩包文件是一闪而过的，大小不一但是都很小只有几十M，是多线程下每个压缩包都还在继续下载嘛？
> > 另外，有个小问题：scripts文件夹下的脚本download_links.sh在被k400.sh调用的时候是download_link.sh哦，作者可以改其中一个，否则会报错不存在。
> > 非常期待得到你的答复！
> > ![微信截图_20211030233220](https://user-images.githubusercontent.com/74886609/139539596-969f592e-cf7a-4928-8c0c-26b36a91716e.png)
> 
> 所有的下载和解压缩都是多进程并行的，准确来说是一个批量一个批量的并行，因为考虑到开太多有些机器性能不好可能会卡，或者网络不好。如果网不好（连aws存储国内偶尔会断连），还是不要直接用k400.sh这个脚本为好，下载部分容易出问题，用个啥下载管理软件把下载链接导进去也好，uget之类的。 每一步操作拆封的对应脚本都在./scripts下，里面的process_num变量可以调整并行的数量，下载和解压都行。
> 
> 十几M的我不确定是不是下载失败了。但是刚开始会自动下载链接的集合、csv标注，这部分只有MB级别的大小。图中的part_###才是视频部分，每个文件1.5GB左右。
> 
> 命名问题是我疏忽了，大概是因为使用pycharm同步，重命名后，推到server上的旧脚本还留着，测试就没有发现问题。感谢～

感谢你的解答，不知你有没有做提取 RGB 帧和光流 呢？想大致了解下这份数据集全部处理好需要多大的空间，我好方便预留足够的空间给它。
再次表示感谢！

**Comment by Yaojie-Shen** [comment]
光流没有提取过，并不了解。但整个视频数据集解压之后会占350GB左右。
解码成RGB图片存储的话，会膨胀特别多，所以我更倾向于配合着用torchvision.io.read_video_timestamps和torchvision.io.read_video直接读视频，但多了解码开销，得看取舍。

**Comment by ImmortalCi** [comment]
因为我是配合mmaction2来进行动作识别的，所以应该是要解码成RGB帧来存储的，谢谢你的解答～！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AcherStyx/kinetics-dataset-downloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 凌晨2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AcherStyx/kinetics-dataset-downloader] some question about getting the kinetics(关于获得数据的一些问题) (Issue #1)





 
光流没有提取过，并不了解。但整个视频数据集解压之后会占350GB左右。
 解码成RGB图片存储的话，会膨胀特别多，所以我更倾向于配合着用torchvision.io.read_video_timestamps和torchvision.io.read_video直接读视频，但多了解码开销，得看取舍。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yaojie-Shen** [comment]
No update, close.
